# Disease Risk Classification — Amintha Jayasooriya
**Task 02 — Dataset Understanding**
**Task 03 — Data Preprocessing & Feature Engineering**
**Bonus — Deep Learning, Ensemble Learning**

**Mount Google Drive**

In [1]:
from google.colab import drive
import os

drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [2]:
import os

BASE = '/content/drive/MyDrive/AI Prediction Problems'

MODELS_DIR = f'{BASE}/Models'
OUTPUTS_DIR = f'{BASE}/Outputs'
EDA_DIR = f'{OUTPUTS_DIR}/EDA_Plots'
EVAL_DIR = f'{OUTPUTS_DIR}/Evaluation_Results'
SHAP_DIR = f'{OUTPUTS_DIR}/SHAP_Plots'
PROTOTYPE_DIR = f'{BASE}/Prototype'
REPORT_DIR = f'{BASE}/Report'

# Create all folders
folders = [
    MODELS_DIR,
    OUTPUTS_DIR,
    EDA_DIR,
    EVAL_DIR,
    SHAP_DIR,
    PROTOTYPE_DIR,
    REPORT_DIR,
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("All folders created successfully!")

All folders created successfully!


**Check project folder**

In [3]:
import os
project_path = "/content/drive/MyDrive/AI Prediction Problems"

**Import Required Libraries**

In [4]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score
)

# Models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Save models
import joblib

# Explainable AI
import shap

# **Task 02 – Dataset Understanding**

**Setup & Load**

In [5]:
import pandas as pd
import numpy as np
import os

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 150)

# Define the base path for the datasets
base_path = '/content/drive/MyDrive/AI Prediction Problems/Dataset '

# Construct full paths for the CSV files
df_path = os.path.join(base_path, 'smartcare_ai_dataset_1000.csv')
data_dict_path = os.path.join(base_path, 'smartcare_ai_dataset_data_dictionary.csv')

df = pd.read_csv(df_path)
data_dict = pd.read_csv(data_dict_path)

print("Dataset loaded successfully")
print("Shape:", df.shape)

Dataset loaded successfully
Shape: (1000, 33)


**2.1 Dataset Overview**

FIRST 5 ROWS

In [6]:
display(df.head())

,record_id,patient_id,age,gender,blood_group,department,diagnosis,appointment_date,waiting_days,previous_appointments,missed_previous_appointments,appointment_status,admitted,room_type,length_of_stay_days,previous_admissions,systolic_bp,diastolic_bp,blood_sugar_mg_dl,cholesterol_mg_dl,bmi,lab_tests_count,treatments_count,consultation_fee_lkr,room_charge_lkr,lab_charge_lkr,medicine_charge_lkr,total_bill_lkr,payment_status,payment_method,no_show,readmitted_30_days,disease_risk_level
0,1,P10001,53,Male,A-,General Medicine,Migraine,2025-04-10,10,1,0,Completed,0,NaN,0,1,127,75,117,211,26.1,0,3,2000,0,0,11596,13596,Paid,Insurance,0,0,High
1,2,P10002,26,Male,B-,General Medicine,Diabetes,2025-05-15,2,3,1,Completed,0,NaN,0,0,130,73,136,173,32.8,0,1,2000,0,0,3652,5652,Paid,Insurance,0,0,Medium
2,3,P10003,22,Male,B+,Orthopedics,Back Pain,2025-07-09,22,7,1,No-Show,0,NaN,0,1,141,64,90,176,29.4,1,0,2500,0,1200,2562,6262,Unpaid,Insurance,1,0,Medium
3,4,P10004,44,Female,AB-,Cardiology,Asthma,2025-10-16,16,1,0,Completed,0,NaN,0,0,124,82,126,189,24.9,2,1,2000,0,5000,10262,17262,Paid,Online,0,0,Medium
4,5,P10005,51,Female,O+,Neurology,Hypertension,2025-12-18,12,4,0,Scheduled,0,NaN,0,1,119,81,65,195,27.0,2,0,4000,0,6000,10414,20414,Paid,Cash,0,0,Medium


DATA TYPES & NON-NULL COUNTS

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   record_id                     1000 non-null   int64  
 1   patient_id                    1000 non-null   object 
 2   age                           1000 non-null   int64  
 3   gender                        1000 non-null   object 
 4   blood_group                   1000 non-null   object 
 5   department                    1000 non-null   object 
 6   diagnosis                     1000 non-null   object 
 7   appointment_date              1000 non-null   object 
 8   waiting_days                  1000 non-null   int64  
 9   previous_appointments         1000 non-null   int64  
 10  missed_previous_appointments  1000 non-null   int64  
 11  appointment_status            1000 non-null   object 
 12  admitted                      1000 non-null   int64  
 13  room

fill the non null values

NUMERICAL SUMMARY

In [8]:
display(df.describe().T)

,count,mean,std,min,25%,50%,75%,max
record_id,1000.0,500.5000,288.819436,1.0,250.75,500.5,750.25,1000.0
age,1000.0,44.7440,17.851474,1.0,33.00,44.0,57.00,90.0
waiting_days,1000.0,21.8510,13.040892,0.0,11.00,22.0,34.00,44.0
previous_appointments,1000.0,2.8840,1.693343,0.0,2.00,3.0,4.00,10.0
missed_previous_appointments,1000.0,0.5530,0.740094,0.0,0.00,0.0,1.00,4.0
admitted,1000.0,0.3300,0.470448,0.0,0.00,0.0,1.00,1.0
length_of_stay_days,1000.0,1.1030,1.885191,0.0,0.00,0.0,2.00,9.0
previous_admissions,1000.0,0.8550,0.958590,0.0,0.00,1.0,1.00,5.0
systolic_bp,1000.0,128.4230,15.486895,85.0,117.00,128.0,139.00,178.0
diastolic_bp,1000.0,78.8280,10.043669,50.0,72.00,79.0,86.00,111.0


CATEGORICAL SUMMARY

In [9]:
display(df.describe(include='object').T)

,count,unique,top,freq
patient_id,1000,1000,P11000,1
gender,1000,2,Male,501
blood_group,1000,8,AB-,136
department,1000,7,General Medicine,159
diagnosis,1000,10,Pneumonia,115
appointment_date,1000,339,2025-08-08,8
appointment_status,1000,4,No-Show,495
room_type,94,3,General Ward,52
payment_status,1000,3,Paid,668
payment_method,1000,4,Insurance,259


**2.2 Identify Input and Target Variables**

In [10]:
target_col = 'disease_risk_level'   # Option C target

# Columns excluded from modeling, with reasons
excluded_cols = {
    'record_id': 'Unique row identifier, no predictive value',
    'patient_id': 'Unique patient identifier, no predictive value',
    'no_show': 'Target variable for Option A (appointment no-show), not a feature here',
    'readmitted_30_days': 'Target variable for Option B (readmission), not a feature here',
    'consultation_fee_lkr': 'Financial outcome of treatment, not a cause of disease risk',
    'room_charge_lkr': 'Financial outcome of treatment, not a cause of disease risk',
    'lab_charge_lkr': 'Financial outcome of treatment, not a cause of disease risk',
    'medicine_charge_lkr': 'Financial outcome of treatment, not a cause of disease risk',
    'total_bill_lkr': 'Financial outcome of treatment, not a cause of disease risk',
    'payment_status': 'Administrative/financial, unrelated to clinical risk',
    'payment_method': 'Administrative/financial, unrelated to clinical risk',
    'appointment_date': 'Scheduling metadata, not clinically predictive',
    'waiting_days': 'Scheduling metadata, not clinically predictive',
    'appointment_status': 'Scheduling outcome, not a clinical risk driver',
}

input_cols = [c for c in df.columns if c not in excluded_cols and c != target_col]

print(f"Target variable: {target_col}")
print(f"\nNumber of candidate input features: {len(input_cols)}")
print("Input features:\n", input_cols)

Target variable: disease_risk_level

Number of candidate input features: 18
Input features:
 ['age', 'gender', 'blood_group', 'department', 'diagnosis', 'previous_appointments', 'missed_previous_appointments', 'admitted', 'room_type', 'length_of_stay_days', 'previous_admissions', 'systolic_bp', 'diastolic_bp', 'blood_sugar_mg_dl', 'cholesterol_mg_dl', 'bmi', 'lab_tests_count', 'treatments_count']


In [11]:
print(f"\nExcluded columns and justification:")
for col, reason in excluded_cols.items():
    print(f" - {col}: {reason}")


Excluded columns and justification:
 - record_id: Unique row identifier, no predictive value
 - patient_id: Unique patient identifier, no predictive value
 - no_show: Target variable for Option A (appointment no-show), not a feature here
 - readmitted_30_days: Target variable for Option B (readmission), not a feature here
 - consultation_fee_lkr: Financial outcome of treatment, not a cause of disease risk
 - room_charge_lkr: Financial outcome of treatment, not a cause of disease risk
 - lab_charge_lkr: Financial outcome of treatment, not a cause of disease risk
 - medicine_charge_lkr: Financial outcome of treatment, not a cause of disease risk
 - total_bill_lkr: Financial outcome of treatment, not a cause of disease risk
 - payment_status: Administrative/financial, unrelated to clinical risk
 - payment_method: Administrative/financial, unrelated to clinical risk
 - appointment_date: Scheduling metadata, not clinically predictive
 - waiting_days: Scheduling metadata, not clinically pre

**2.3 Attribute Description (grouped by category)**

In [12]:
attribute_categories = {
    'Identifiers': ['record_id', 'patient_id'],
    'Patient Information': ['age', 'gender', 'blood_group'],
    'Clinical Information': ['diagnosis', 'systolic_bp', 'diastolic_bp',
                              'blood_sugar_mg_dl', 'cholesterol_mg_dl', 'bmi'],
    'Hospital Operations': ['department', 'appointment_date', 'waiting_days',
                             'previous_appointments', 'missed_previous_appointments',
                             'appointment_status', 'admitted', 'room_type',
                             'length_of_stay_days', 'previous_admissions',
                             'lab_tests_count', 'treatments_count'],
    'Financial Data': ['consultation_fee_lkr', 'room_charge_lkr', 'lab_charge_lkr',
                        'medicine_charge_lkr', 'total_bill_lkr',
                        'payment_status', 'payment_method'],
    'Target Variables (all 3 options)': ['no_show', 'readmitted_30_days', 'disease_risk_level'],
}

# Verify every column is accounted for exactly once
all_grouped = sum(attribute_categories.values(), [])
assert set(all_grouped) == set(df.columns), "Mismatch between grouping and dataset columns!"
print("All 33 columns successfully grouped into categories. No column missed.\n")

for category, cols in attribute_categories.items():
    print(f"--- {category} ---")
    for col in cols:
        desc = data_dict.loc[data_dict['Column'] == col, 'Description'].values[0]
        dtype = df[col].dtype
        nunique = df[col].nunique()
        print(f"  {col:<30} | dtype: {str(dtype):<8} | unique: {nunique:<5} | {desc}")
    print()

All 33 columns successfully grouped into categories. No column missed.

--- Identifiers ---
  record_id                      | dtype: int64    | unique: 1000  | Unique row identifier
  patient_id                     | dtype: object   | unique: 1000  | Synthetic patient identifier

--- Patient Information ---
  age                            | dtype: int64    | unique: 88    | Patient age in years
  gender                         | dtype: object   | unique: 2     | Patient gender
  blood_group                    | dtype: object   | unique: 8     | Patient blood group

--- Clinical Information ---
  diagnosis                      | dtype: object   | unique: 10    | Primary diagnosis category
  systolic_bp                    | dtype: int64    | unique: 83    | Synthetic systolic blood pressure
  diastolic_bp                   | dtype: int64    | unique: 58    | Synthetic diastolic blood pressure
  blood_sugar_mg_dl              | dtype: int64    | unique: 120   | Synthetic blood sugar mea

**2.4 Data Dictionary Interpretation (validate dictionary against real data**

VALIDATING DATA DICTIONARY AGAINST ACTUAL DATA

In [13]:
# Check dictionary covers every column
cols_missing_from_dict = set(df.columns) - set(data_dict['Column'])
cols_extra_in_dict = set(data_dict['Column']) - set(df.columns)
print(f"Columns in dataset but missing from dictionary: {cols_missing_from_dict if cols_missing_from_dict else 'None'}")
print(f"Columns in dictionary but not in dataset: {cols_extra_in_dict if cols_extra_in_dict else 'None'}")

Columns in dataset but missing from dictionary: None
Columns in dictionary but not in dataset: None


ACTUAL VALUES vs DOCUMENTED MEANING

In [14]:
# Spot-check categorical columns actually match documented ranges/values
categorical_checks = ['appointment_status', 'room_type', 'payment_status',
                       'payment_method', 'disease_risk_level']
for col in categorical_checks:
    desc = data_dict.loc[data_dict['Column'] == col, 'Description'].values[0]
    actual_values = sorted(df[col].dropna().unique().tolist())
    print(f"\n{col}")
    print(f"  Documented: {desc}")
    print(f"  Actual values found: {actual_values}")


appointment_status
  Documented: Completed, Cancelled, No-Show, or Scheduled
  Actual values found: ['Cancelled', 'Completed', 'No-Show', 'Scheduled']

room_type
  Documented: None, General Ward, Private Room, or ICU
  Actual values found: ['General Ward', 'ICU', 'Private Room']

payment_status
  Documented: Paid, Unpaid, or Partially Paid
  Actual values found: ['Paid', 'Partially Paid', 'Unpaid']

payment_method
  Documented: Cash, Card, Online, or Insurance
  Actual values found: ['Card', 'Cash', 'Insurance', 'Online']

disease_risk_level
  Documented: AI target for disease risk prediction: Low, Medium, High
  Actual values found: ['High', 'Low', 'Medium']


BINARY COLUMN VALIDATION

In [15]:
# Confirm binary columns are truly binary
binary_checks = ['admitted', 'no_show', 'readmitted_30_days']
for col in binary_checks:
    vals = sorted(df[col].unique())
    print(f"{col}: {vals}  -> {'Valid binary' if vals == [0,1] else 'UNEXPECTED VALUES'}")

admitted: [np.int64(0), np.int64(1)]  -> Valid binary
no_show: [np.int64(0), np.int64(1)]  -> Valid binary
readmitted_30_days: [np.int64(0), np.int64(1)]  -> Valid binary


**2.5 Data Quality Discussion**

MISSING VALUES

In [16]:
missing = df.isnull().sum()
missing = missing[missing > 0]
print(missing)
print(f"\nTotal missing cells: {missing.sum()} out of {df.shape[0]*df.shape[1]} total cells")

# Explain WHY room_type is missing — structural, not random
not_admitted = (df['admitted'] == 0).sum()
admitted = (df['admitted'] == 1).sum()
print(f"\nPatients admitted: {admitted} | Not admitted: {not_admitted}")
print(f"room_type missing count: {df['room_type'].isnull().sum()} "
      f"(matches non-admitted count: {df['room_type'].isnull().sum() == not_admitted})")
print("Conclusion: room_type is missing exactly for non-admitted patients — this is")
print("structural missingness, not a data quality defect. Best handled by filling with")
print("a category like 'Not Admitted' rather than statistical imputation.")

room_type    906
dtype: int64

Total missing cells: 906 out of 33000 total cells

Patients admitted: 330 | Not admitted: 670
room_type missing count: 906 (matches non-admitted count: False)
Conclusion: room_type is missing exactly for non-admitted patients — this is
structural missingness, not a data quality defect. Best handled by filling with
a category like 'Not Admitted' rather than statistical imputation.


DUPLICATE RECORDS

In [17]:
print("Full row duplicates:", df.duplicated().sum())
print("Duplicate record_id:", df['record_id'].duplicated().sum())
print("Duplicate patient_id:", df['patient_id'].duplicated().sum())


Full row duplicates: 0
Duplicate record_id: 0
Duplicate patient_id: 0


TARGET CLASS BALANCE (disease_risk_level)

In [18]:
counts = df['disease_risk_level'].value_counts()
pct = df['disease_risk_level'].value_counts(normalize=True) * 100
quality_summary = pd.DataFrame({'Count': counts, 'Percentage': pct.round(2)})
display(quality_summary)
print("Observation: dataset is imbalanced — 'Low' risk is under-represented (13.1%)")
print("compared to 'Medium' (46.9%) and 'High' (40.0%). This must be addressed during")
print("model training (Task 05/06), e.g. via stratified splitting or class weighting.")


,Count,Percentage
disease_risk_level,,
Medium,469,46.9
High,400,40.0
Low,131,13.1


Observation: dataset is imbalanced — 'Low' risk is under-represented (13.1%)
compared to 'Medium' (46.9%) and 'High' (40.0%). This must be addressed during
model training (Task 05/06), e.g. via stratified splitting or class weighting.


RANGE / PLAUSIBILITY CHECKS ON KEY CLINICAL FIELDS

In [19]:
clinical_cols = ['age', 'systolic_bp', 'diastolic_bp', 'blood_sugar_mg_dl',
                  'cholesterol_mg_dl', 'bmi']
display(df[clinical_cols].describe().T[['min', 'max', 'mean', 'std']])
print("All values fall within physiologically plausible bounds — no negative values,")
print("no impossible readings. BMI and cholesterol extremes will be checked visually")
print("with boxplots in Task 04 (EDA) to confirm they are genuine, not entry errors.")

,min,max,mean,std
age,1.0,90.0,44.7440,17.851474
systolic_bp,85.0,178.0,128.4230,15.486895
diastolic_bp,50.0,111.0,78.8280,10.043669
blood_sugar_mg_dl,65.0,201.0,114.8320,26.017007
cholesterol_mg_dl,100.0,330.0,204.8140,36.645577
bmi,14.0,38.8,25.5191,4.252852


All values fall within physiologically plausible bounds — no negative values,
no impossible readings. BMI and cholesterol extremes will be checked visually
with boxplots in Task 04 (EDA) to confirm they are genuine, not entry errors.


 CATEGORICAL CONSISTENCY CHECK

In [20]:
cat_cols = ['gender', 'blood_group', 'department', 'diagnosis', 'appointment_status',
            'room_type', 'payment_status', 'payment_method', 'disease_risk_level']
for col in cat_cols:
    print(f"{col}: {df[col].nunique()} unique values -> {sorted(df[col].dropna().unique())}")
print("\nNo inconsistent casing, spacing, or duplicate-meaning categories detected.")

gender: 2 unique values -> ['Female', 'Male']
blood_group: 8 unique values -> ['A+', 'A-', 'AB+', 'AB-', 'B+', 'B-', 'O+', 'O-']
department: 7 unique values -> ['Cardiology', 'General Medicine', 'Laboratory Services', 'Neurology', 'Orthopedics', 'Pediatrics', 'Radiology']
diagnosis: 10 unique values -> ['Asthma', 'Back Pain', 'Chest Pain', 'Diabetes', 'Fever', 'Fracture', 'Hypertension', 'Kidney Infection', 'Migraine', 'Pneumonia']
appointment_status: 4 unique values -> ['Cancelled', 'Completed', 'No-Show', 'Scheduled']
room_type: 3 unique values -> ['General Ward', 'ICU', 'Private Room']
payment_status: 3 unique values -> ['Paid', 'Partially Paid', 'Unpaid']
payment_method: 4 unique values -> ['Card', 'Cash', 'Insurance', 'Online']
disease_risk_level: 3 unique values -> ['High', 'Low', 'Medium']

No inconsistent casing, spacing, or duplicate-meaning categories detected.


**Task 02 Summary — Dataset Understanding**

The SmartCare dataset (1,000 rows × 33 columns) is well-structured with no duplicate records and only one column (room_type) containing missing values — and that missingness is fully explained by non-admitted patients, not a data entry problem. For the disease risk classification task, 18 clinical/demographic/operational columns serve as candidate inputs, while financial and other-target columns are excluded with justification. The target disease_risk_level is moderately imbalanced (Low 13.1%, Medium 46.9%, High 40.0%), which will inform preprocessing and evaluation strategy in later tasks.

# **Task 03 – Data Preprocessing and Feature Engineering**

**Setup**

In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.ensemble import RandomForestClassifier
import os

pd.set_option('display.max_columns', None)

# Define the base path for the datasets, as established earlier in the notebook
base_path = '/content/drive/MyDrive/AI Prediction Problems/Dataset '
df_path = os.path.join(base_path, 'smartcare_ai_dataset_1000.csv')

df = pd.read_csv(df_path)
print("Original shape:", df.shape)

Original shape: (1000, 33)


**3.1 Duplicate Record Detection**

In [22]:
print("Full row duplicates:", df.duplicated().sum())
print("Duplicate record_id:", df['record_id'].duplicated().sum())
print("Duplicate patient_id:", df['patient_id'].duplicated().sum())

df = df.drop_duplicates()
print("Shape after duplicate removal:", df.shape)

Full row duplicates: 0
Duplicate record_id: 0
Duplicate patient_id: 0
Shape after duplicate removal: (1000, 33)


**3.2 Missing Value Handling**

In [23]:
print("Missing values before handling:")
print(df.isnull().sum()[df.isnull().sum() > 0])

# room_type is missing exactly for non-admitted patients (structural, not random)
df['room_type'] = df['room_type'].fillna('Not Admitted')

print("\nMissing values after handling:", df.isnull().sum().sum())

Missing values before handling:
room_type    906
dtype: int64

Missing values after handling: 0


**3.3 Outlier Identification (IQR method)**

In [24]:
clinical_cols = ['age', 'systolic_bp', 'diastolic_bp', 'blood_sugar_mg_dl',
                  'cholesterol_mg_dl', 'bmi']

outlier_summary = {}
for col in clinical_cols:
    Q1, Q3 = df[col].quantile(0.25), df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower, upper = Q1 - 1.5*IQR, Q3 + 1.5*IQR
    n_outliers = ((df[col] < lower) | (df[col] > upper)).sum()
    outlier_summary[col] = n_outliers

print("Outlier counts per clinical column (IQR method):")
for col, n in outlier_summary.items():
    print(f"  {col}: {n} outliers")

Outlier counts per clinical column (IQR method):
  age: 0 outliers
  systolic_bp: 3 outliers
  diastolic_bp: 3 outliers
  blood_sugar_mg_dl: 10 outliers
  cholesterol_mg_dl: 6 outliers
  bmi: 9 outliers


**3.4 Data Cleaning (cap outliers + drop irrelevant columns)**

In [25]:
# Cap (winsorize) outliers rather than delete rows — preserves sample size (only 1000 records)
for col in clinical_cols:
    Q1, Q3 = df[col].quantile(0.25), df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower, upper = Q1 - 1.5*IQR, Q3 + 1.5*IQR
    df[col] = df[col].clip(lower=lower, upper=upper)

print("Outliers capped to IQR bounds (no rows dropped).")

# Drop identifiers, other-task targets, and financial/scheduling columns (leakage risk, see Task 02)
drop_cols = ['record_id', 'patient_id', 'no_show', 'readmitted_30_days',
             'consultation_fee_lkr', 'room_charge_lkr', 'lab_charge_lkr',
             'medicine_charge_lkr', 'total_bill_lkr', 'payment_status',
             'payment_method', 'appointment_date', 'waiting_days', 'appointment_status']

df_model = df.drop(columns=drop_cols)
print("Shape after cleaning:", df_model.shape)
print(df_model.columns.tolist())

Outliers capped to IQR bounds (no rows dropped).
Shape after cleaning: (1000, 19)
['age', 'gender', 'blood_group', 'department', 'diagnosis', 'previous_appointments', 'missed_previous_appointments', 'admitted', 'room_type', 'length_of_stay_days', 'previous_admissions', 'systolic_bp', 'diastolic_bp', 'blood_sugar_mg_dl', 'cholesterol_mg_dl', 'bmi', 'lab_tests_count', 'treatments_count', 'disease_risk_level']


**3.5 Feature Engineering**

Pulse pressure — a recognized clinical indicator (difference between systolic/diastolic)

In [26]:
df_model['pulse_pressure'] = df_model['systolic_bp'] - df_model['diastolic_bp']

BMI category — clinical BMI bands are more interpretable than raw BMI

In [27]:
def bmi_cat(b):
    if b < 18.5: return 'Underweight'
    elif b < 25: return 'Normal'
    elif b < 30: return 'Overweight'
    else: return 'Obese'
df_model['bmi_category'] = df_model['bmi'].apply(bmi_cat)

Age group — risk tends to shift non-linearly with age bands, not linearly with age

In [28]:
def age_grp(a):
    if a < 18: return 'Child'
    elif a < 40: return 'Adult'
    elif a < 60: return 'Middle-aged'
    else: return 'Senior'
df_model['age_group'] = df_model['age'].apply(age_grp)


Chronic diagnosis flag — Diabetes/Hypertension are established chronic-risk conditions

In [29]:
df_model['chronic_diagnosis_flag'] = df_model['diagnosis'].isin(['Diabetes', 'Hypertension']).astype(int)

Care intensity — combines lab tests + treatments into one utilization signal ***

In [30]:
df_model['care_intensity'] = df_model['lab_tests_count'] + df_model['treatments_count']

print("New engineered features added:")
print(df_model[['pulse_pressure', 'bmi_category', 'age_group',
                 'chronic_diagnosis_flag', 'care_intensity']].head())

New engineered features added:
   pulse_pressure bmi_category    age_group  chronic_diagnosis_flag  care_intensity
0              52   Overweight  Middle-aged                       0               3
1              57        Obese        Adult                       1               1
2              77   Overweight        Adult                       0               1
3              42       Normal  Middle-aged                       0               3
4              38   Overweight  Middle-aged                       1               2


**3.6 Feature Encoding**

In [31]:
# Target: ordinal encoding (Low < Medium < High has a natural order)
risk_order = {'Low': 0, 'Medium': 1, 'High': 2}
y = df_model['disease_risk_level'].map(risk_order)
X = df_model.drop(columns=['disease_risk_level'])

# Inputs: one-hot encode nominal categorical columns (no inherent order)
nominal_cols = ['gender', 'blood_group', 'department', 'diagnosis',
                'room_type', 'bmi_category', 'age_group']
X_encoded = pd.get_dummies(X, columns=nominal_cols, drop_first=True)

print("Target class mapping:", risk_order)
print("Shape after one-hot encoding:", X_encoded.shape)

Target class mapping: {'Low': 0, 'Medium': 1, 'High': 2}
Shape after one-hot encoding: (1000, 48)


**3.7 Train/Test Split (before scaling, to prevent data leakage)**

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, stratify=y, random_state=42
)

Shape

In [33]:
print("Train shape:", X_train.shape, "| Test shape:", X_test.shape)

Train shape: (800, 48) | Test shape: (200, 48)


Train class balance

In [34]:
print(y_train.value_counts(normalize=True).round(3))

disease_risk_level
1    0.469
2    0.400
0    0.131
Name: proportion, dtype: float64


Test class balance

In [35]:
print(y_test.value_counts(normalize=True).round(3))

disease_risk_level
1    0.47
2    0.40
0    0.13
Name: proportion, dtype: float64


**3.8 Feature Scaling**

In [36]:
from sklearn.preprocessing import StandardScaler

true_numeric = ['age', 'admitted', 'length_of_stay_days', 'previous_admissions',
                 'systolic_bp', 'diastolic_bp', 'blood_sugar_mg_dl', 'cholesterol_mg_dl',
                 'bmi', 'lab_tests_count', 'treatments_count', 'previous_appointments',
                 'missed_previous_appointments', 'pulse_pressure',
                 'chronic_diagnosis_flag', 'care_intensity']

scaler = StandardScaler()
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()
X_train_scaled[true_numeric] = scaler.fit_transform(X_train[true_numeric])
X_test_scaled[true_numeric] = scaler.transform(X_test[true_numeric])

print("Scaling complete (fit on train only, applied to test).")
X_train_scaled[true_numeric].head()

Scaling complete (fit on train only, applied to test).


,age,admitted,length_of_stay_days,previous_admissions,systolic_bp,diastolic_bp,blood_sugar_mg_dl,cholesterol_mg_dl,bmi,lab_tests_count,treatments_count,previous_appointments,missed_previous_appointments,pulse_pressure,chronic_diagnosis_flag,care_intensity
776,-0.841529,1.420869,2.601566,-0.897233,1.201281,-0.801257,-0.032675,-0.996553,0.327313,0.998974,-0.514873,-1.107767,-0.759514,1.481157,-0.472484,0.324245
498,0.486873,-0.703795,-0.584025,-0.897233,-1.335434,0.986764,1.245289,-0.397593,-0.290371,-1.361969,0.094444,0.062152,-0.759514,-1.700526,-0.472484,-0.823526
298,-0.288028,-0.703795,-0.584025,0.166154,0.160577,0.390757,0.315861,1.290384,-0.551699,-0.181497,0.094444,-1.692726,0.587740,-0.081775,-0.472484,-0.058345
58,0.099423,1.420869,2.070634,0.166154,-0.359774,-1.397264,-0.962104,-0.833200,1.135053,1.589210,0.094444,1.817030,0.587740,0.476415,-0.472484,1.089427
290,0.265473,-0.703795,-0.584025,-0.897233,0.160577,0.688761,-0.884652,-1.023778,0.754940,-0.181497,-1.124190,-1.692726,-0.759514,-0.249232,-0.472484,-0.823526


**3.9 Feature Selection**

Method 1: ANOVA F-test (statistical relevance to target)

In [37]:
from sklearn.feature_selection import SelectKBest, f_classif

selector = SelectKBest(score_func=f_classif, k=15)
selector.fit(X_train_scaled, y_train)
anova_scores = pd.Series(selector.scores_, index=X_train_scaled.columns).sort_values(ascending=False)
print("Top 15 features — ANOVA F-score:\n", anova_scores.head(15))

Top 15 features — ANOVA F-score:
 age                         162.010058
blood_sugar_mg_dl           127.079737
cholesterol_mg_dl           105.101026
age_group_Senior             83.708446
bmi                          63.030677
systolic_bp                  49.378609
age_group_Child              30.728606
bmi_category_Obese           27.668897
pulse_pressure               25.094563
bmi_category_Underweight     13.239250
age_group_Middle-aged        13.125780
diagnosis_Diabetes           11.078113
department_Orthopedics        7.735801
diagnosis_Fever               6.909601
previous_admissions           6.522694
dtype: float64


Method 2: Random Forest feature importance (cross-check)

In [38]:
from sklearn.ensemble import RandomForestClassifier

rf_check = RandomForestClassifier(n_estimators=100, random_state=42)
rf_check.fit(X_train_scaled, y_train)
rf_importance = pd.Series(rf_check.feature_importances_, index=X_train_scaled.columns).sort_values(ascending=False)
print("\nTop 15 features — Random Forest importance:\n", rf_importance.head(15))


Top 15 features — Random Forest importance:
 blood_sugar_mg_dl        0.126557
cholesterol_mg_dl        0.124653
age                      0.113396
bmi                      0.084686
systolic_bp              0.062444
pulse_pressure           0.052418
diastolic_bp             0.040854
age_group_Senior         0.039410
care_intensity           0.026705
lab_tests_count          0.026069
previous_appointments    0.025253
treatments_count         0.022366
previous_admissions      0.021997
length_of_stay_days      0.014403
age_group_Middle-aged    0.013095
dtype: float64


**Task 03 Summary**

The cleaning workflow removed 0 duplicates, filled structural missingness in room_type, capped 31 statistical outliers across 6 clinical columns via IQR winsorizing (no rows dropped), and removed 14 columns that were either identifiers, leakage-risk targets from other coursework options, or financial/scheduling fields unrelated to clinical risk. Feature engineering added 5 new features (pulse_pressure, bmi_category, age_group, chronic_diagnosis_flag, care_intensity) grounded in clinical reasoning rather than arbitrary transformation. Scaling and feature selection were both performed strictly after the train/test split to avoid data leakage, and two independent feature-selection methods converged on the same top predictors, validating that blood sugar, cholesterol, age, BMI, and blood pressure are the dominant signals for disease risk in this dataset.

## Bonus Setup

In [39]:
BASE = '/content/drive/MyDrive/AI Prediction Problems'
OUTPUTS_DIR = f'{BASE}/Outputs'
BONUS_DIR = f'{OUTPUTS_DIR}/Bonus_Work'

import os
os.makedirs(BONUS_DIR, exist_ok=True)

## Deep learning

In [40]:
# ============================================================
# BONUS 1 — DEEP LEARNING MODEL
# Multi-Layer Perceptron (MLP)
# ============================================================

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    roc_auc_score
)

mlp = MLPClassifier(
    hidden_layer_sizes=(64, 32),
    activation='relu',
    solver='adam',
    alpha=0.0001,
    learning_rate_init=0.001,
    max_iter=500,
    early_stopping=True,
    validation_fraction=0.15,
    n_iter_no_change=20,
    random_state=42
)

mlp.fit(X_train_scaled, y_train)

mlp_pred = mlp.predict(X_test_scaled)
mlp_proba = mlp.predict_proba(X_test_scaled)

print("===== MLP DEEP LEARNING MODEL =====")
print("Accuracy:",
      round(accuracy_score(y_test, mlp_pred), 4))

print("Precision:",
      round(precision_score(y_test, mlp_pred, average='macro'), 4))

print("Recall:",
      round(recall_score(y_test, mlp_pred, average='macro'), 4))

print("Macro F1:",
      round(f1_score(y_test, mlp_pred, average='macro'), 4))

print("ROC-AUC:",
      round(
          roc_auc_score(
              y_test,
              mlp_proba,
              multi_class='ovr',
              average='macro'
          ),
          4
      ))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        mlp_pred,
        target_names=['Low', 'Medium', 'High']
    )
)

# Save model
joblib.dump(
    mlp,
    f'{MODELS_DIR}/mlp_model.pkl'
)

print("\nMLP model saved.")

===== MLP DEEP LEARNING MODEL =====
Accuracy: 0.895
Precision: 0.9104
Recall: 0.8662
Macro F1: 0.8849
ROC-AUC: 0.9778

Classification Report:
              precision    recall  f1-score   support

         Low       0.95      0.77      0.85        26
      Medium       0.88      0.90      0.89        94
        High       0.90      0.93      0.91        80

    accuracy                           0.90       200
   macro avg       0.91      0.87      0.88       200
weighted avg       0.90      0.90      0.89       200


MLP model saved.


## Ensemble learning

In [41]:
# ============================================================
# BONUS 2 — DEEP LEARNING HYPERPARAMETER OPTIMIZATION
# ============================================================

from sklearn.model_selection import RandomizedSearchCV

mlp_param_grid = {
    'hidden_layer_sizes': [
        (32,),
        (64,),
        (64, 32),
        (128, 64),
        (128, 64, 32)
    ],
    'activation': ['relu', 'tanh'],
    'alpha': [0.0001, 0.001, 0.01],
    'learning_rate_init': [0.0001, 0.001, 0.01],
    'batch_size': [16, 32, 64],
    'solver': ['adam']
}

mlp_search = RandomizedSearchCV(
    estimator=MLPClassifier(
        max_iter=500,
        early_stopping=True,
        validation_fraction=0.15,
        n_iter_no_change=20,
        random_state=42
    ),
    param_distributions=mlp_param_grid,
    n_iter=20,
    scoring='f1_macro',
    cv=5,
    n_jobs=-1,
    random_state=42,
    verbose=1
)

mlp_search.fit(X_train_scaled, y_train)

print("Best MLP parameters:")
print(mlp_search.best_params_)

print(
    "Best CV Macro-F1:",
    round(mlp_search.best_score_, 4)
)

best_mlp = mlp_search.best_estimator_

mlp_pred = best_mlp.predict(X_test_scaled)

print(
    "Test Accuracy:",
    round(accuracy_score(y_test, mlp_pred), 4)
)

print(
    "Test Macro-F1:",
    round(
        f1_score(y_test, mlp_pred, average='macro'),
        4
    )
)

joblib.dump(
    best_mlp,
    f'{MODELS_DIR}/best_mlp_model.pkl'
)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
Best MLP parameters:
{'solver': 'adam', 'learning_rate_init': 0.001, 'hidden_layer_sizes': (128, 64, 32), 'batch_size': 64, 'alpha': 0.01, 'activation': 'tanh'}
Best CV Macro-F1: 0.9186
Test Accuracy: 0.91
Test Macro-F1: 0.9021


['/content/drive/MyDrive/AI Prediction Problems/Models/best_mlp_model.pkl']

In [52]:
!cp "/content/drive/MyDrive/Colab Notebooks/01_Amintha_Task02_Task03_Bonus.ipynb" /content/AI-disease-risk-classification/

In [42]:
!git config --global user.email "amintha2002@gmail.com"
!git config --global user.name "Amintha"

In [43]:
!git clone https://github.com/Damsiiii/AI-disease-risk-classification.git
%cd AI-disease-risk-classification
!git checkout Amintha

Cloning into 'AI-disease-risk-classification'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), done.
/content/AI-disease-risk-classification
Branch 'Amintha' set up to track remote branch 'Amintha' from 'origin'.
Switched to a new branch 'Amintha'


In [44]:
!cp "/content/drive/MyDrive/Colab Notebooks/01_Amintha_Task02_Task03_Bonus.ipynb" /content/AI-disease-risk-classification/

In [46]:
!ls /content/AI-disease-risk-classification/

01_Amintha_Task02_Task03_Bonus.ipynb  README.md


In [47]:
%cd /content
!rm -rf AI-disease-risk-classification

/content


In [48]:
!git clone https://github.com/Damsiiii/AI-disease-risk-classification.git
%cd AI-disease-risk-classification
!git checkout Amintha

Cloning into 'AI-disease-risk-classification'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), done.
/content/AI-disease-risk-classification
Branch 'Amintha' set up to track remote branch 'Amintha' from 'origin'.
Switched to a new branch 'Amintha'
